version: "3.7"

volumes:
  cs2-data:
    name: cs2-data

services:
  cs2:
    image: soren90/cs2:latest
    container_name: cs2-ds

    environment:
      SERVER_HOSTNAME: "Counter-strike 2 Dedicated server"
      SERVER_PASSWORD: "PASSWORD"
      RCON_PASSWORD: "PASSWORD"
      IP: 0.0.0.0
      PORT: 27015
      GAME_TYPE: 0
      GAME_MODE: 1
      MAP: de_dust2
      MAXPLAYERS: 12
      TOKEN: DB8B4AFD4D55E2D7F7B1A83A2AA7E9EF
      EXTRAARG: #Extra Launch options

    volumes:
      - type: volume
        source: cs2-data
        target: /mnt/server

    network_mode: "host"

    restart: unless-stopped
    stdin_open: true
    tty: true

