
#!/bin/bash

# Set defaults
ENV SERVER_HOSTNAME=$SERVER_HOSTNAME
ENV SERVER_PASSWORD=SERVER_PASSWORD
ENV RCON_PASSWORD=RCON_PASSWORD
ENV IP=IP
ENV PORT=PORT
ENV GAME_TYPE=GAME_TYPE
ENV GAME_MODE=GAME_MODE
ENV MAP=MAP
ENV MAXPLAYERS=MAXPLAYERS
ENV TOKEN=TOKEN
ENV EXTRAARG=EXTRAARG
